set(BENCHMARKS_STARLING ${BENCHMARKS}.Starling)
##############################################################################
# Multithread benchmarks
##############################################################################
add_subdirectory(resource_pool)
add_subdirectory(disruptor)
##############################################################################
