set(BENCHMARKS_MULTITHREAD ${BENCHMARKS}.Multithread)
##############################################################################
# Multithread benchmarks
##############################################################################
add_subdirectory(resource_pool)
add_subdirectory(disruptor)
##############################################################################
