set(COMMON ${PROJECT_NAME}.Common)

###############################################

add_subdirectory(core-beaver)

add_subdirectory(serialization-pangolin)

add_subdirectory(crypto-pufferfish)

add_subdirectory(multithread)

add_subdirectory(render-chameleon)

add_subdirectory(logger-crow)

add_subdirectory(3rdparty)

add_subdirectory(chrono)

add_subdirectory(math)

add_subdirectory(locator-spider)

add_subdirectory(algorithms)