set(COMMON ${PROJECT_NAME}.Common)

###############################################

add_subdirectory(beavers)

add_subdirectory(serialization)

add_subdirectory(crypto)

add_subdirectory(multithread)

add_subdirectory(chameleon)

add_subdirectory(crow)

add_subdirectory(3rdparty)

add_subdirectory(chrono)

add_subdirectory(math)

add_subdirectory(spider)

add_subdirectory(algorithms)